/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package problembuilder;

import java.util.*;
import java.awt.event.ActionEvent;
import java.io.*;
import javax.swing.*;
/**
 *
 * @author iqapp
 */
public class MainWin extends javax.swing.JFrame {

    /**
     * Creates new form MainWin
     */
    private final ArrayList<CategoryPanel> categoryPanels;
    private ObjectOutputStream questionFileOutput;
    private ObjectInputStream questionFileInput;
    private ArrayList<Category> categories;
    private int categoryIndex, questionIndex;
    public boolean newQuestionCreated;
    
    public MainWin() {
        initComponents();
        categoryPanels = new ArrayList();
        categoryIndex = -1;
        questionIndex = -1;
        categories = new ArrayList();
        File questionFile = new File(fileNameText.getText());
        try{    
            if(questionFile.exists()){
                try{
                    questionFileInput = new ObjectInputStream(new FileInputStream(questionFile));
                    categories = (ArrayList<Category>)questionFileInput.readObject();
                }catch(ClassNotFoundException | IOException e){

                }
            }
            questionFileOutput = new ObjectOutputStream(new FileOutputStream(questionFile));
        }catch(IOException e){
            System.exit(1);
        }
        
        initCategoryPanel();
    }

    private void initCategoryPanel(){
        for(Category category : categories){
            CategoryPanel newCategoryPanel = this.addNewCategoryPanel(category.getCategoryText());
            for(Question question : category.questions)
                addNewQuestionButton(newCategoryPanel, Integer.toString(question.credits));
            
            this.addNewQuestionButton(newCategoryPanel, "+");
        }
        this.addNewQuestionButton(addNewCategoryPanel(""), "+");
    }
    
    private void addNewQuestionButton(CategoryPanel parentPanel, String text){
        QuestionButton newButton = parentPanel.addNewQuestionButton(text);
        newButton.addActionListener(this::buttonAction);
    }
    
    private CategoryPanel addNewCategoryPanel(String categoryText){
        CategoryPanel newCategoryPanel = new CategoryPanel(categoryText, categoryPanels.size());
        newCategoryPanel.categoryTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                categoryTextFieldFocusLost(evt);
            }
        });
        mainPanel.add(newCategoryPanel);
        categoryPanels.add(newCategoryPanel);
        
        return newCategoryPanel;
    }
    
    public void categoryTextFieldFocusLost(java.awt.event.FocusEvent evt){
        JTextField sourceTextField = (JTextField)evt.getSource();
        CategoryPanel sourcePanel = (CategoryPanel)sourceTextField.getParent();
        if(sourcePanel.categoryIndex < categories.size())
            categories.get(sourcePanel.categoryIndex).setCategoryText(sourceTextField.getText());
        else{
            Category newCategory = new Category(sourceTextField.getText());
            categories.add(newCategory);
            this.addNewQuestionButton(this.addNewCategoryPanel(""), "+");
        }
    }
    
    public void buttonAction(ActionEvent evt){
        QuestionButton clickedButton = (QuestionButton) evt.getSource();
        this.categoryIndex = ((CategoryPanel)clickedButton.getParent()).categoryIndex;
        this.questionIndex = clickedButton.questionIndex;
        new QuestionWin(this).setVisible(true);
        this.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPanel = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();
        fileNameText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1280, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        mainPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        scrollPanel.setViewportView(mainPanel);

        fileNameText.setText("Question1.ser");

        jButton1.setText("New File");

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(fileNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        if(categoryIndex >= 0 && questionIndex >= 0){
            int credits = this.categories.get(categoryIndex).questions.get(questionIndex).credits;
            categoryPanels.get(categoryIndex).questionButtons.get(questionIndex).setText(Integer.toString(credits));
        }
    }//GEN-LAST:event_formWindowActivated

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            questionFileOutput.writeObject(this.categories);
            questionFileOutput.close();
        }catch(IOException e){
            System.exit(1);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public int getCategoryIndex(){
        return this.categoryIndex;
    }
    
    public int getQuestionIndex(){
        return this.questionIndex;
    }
    
    public ArrayList<Category> getCategories(){
        return this.categories;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fileNameText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JScrollPane scrollPanel;
    // End of variables declaration//GEN-END:variables
}
